In [1]:
# 토크나이징
# nltk
!pip install nltk

   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------- 1.5/1.5 MB 9.9 MB/s eta 0:00:00


In [6]:
import nltk
nltk.download("all", quiet=True)

True

In [9]:
# word_tokenize : 단어 단위로 토큰 분리, sent_tokenize : 문장 단위로 토큰 분리
from nltk.tokenize import word_tokenize

# text = "apple, pear, orange, i bought 3 apple"
text = "사과, 배, 오렌지, 나는 3개의 사과를 구입했다"
print(word_tokenize(text))

['사과', ',', '배', ',', '오렌지', ',', '나는', '3개의', '사과를', '구입했다']


In [8]:
from nltk.tokenize import sent_tokenize

text= """삼성전자의 뒤를 이어 KT(1218억원), 쿠팡(660억원)도 지난해와 순위가 같았다. 나머지 기업들은 10위 권 내에서 순위 변동이 있었다. 지난해까지 4위와 5위였던 SK하이닉스와 SK텔레콤은 각각 6위와 7위로 밀려났고, 그 자리는 삼성SDS와 LG U+가 차지했다.

정보 보호 전담 인력은 삼성전자, KT, 삼성SDS 순으로 많았다. 공시 대상 기업 전체의 올해 정보 보호 투자액은 2조1196억원, 전담 인력은 7681.4명으로 지난해보다 각각 15.7%, 13.9% 증가했다. 평균 투자액(29억원)과 평균 전담 인력(10.5명)도 지난해보다 늘었다.

정보 보호에 대한 기업의 사회적 책임이 강조됨에 따라 자율 공시 기업의 수도 지난해 63개에서 91개로 늘었다.

업종별 평균 투자액은 금융업(76억원), 정보통신업(59억원), 도소매업(27억원) 순으로 많았다.

류제명 과학기술정보통신부 네트워크정책실장은 "정보보호 공시 제도가 기업의 정보보호 수준 제고에 기여하고 있음을 기업들의 자발적인 정보보호 투자 확대를 통해 확인할 수 있었다"며 "정부는 공시 내용 검증을 통해 정확한 정보를 이용자에게 제공할 것"이라고 말했다."""
print(sent_tokenize(text))

['삼성전자의 뒤를 이어 KT(1218억원), 쿠팡(660억원)도 지난해와 순위가 같았다.', '나머지 기업들은 10위 권 내에서 순위 변동이 있었다.', '지난해까지 4위와 5위였던 SK하이닉스와 SK텔레콤은 각각 6위와 7위로 밀려났고, 그 자리는 삼성SDS와 LG U+가 차지했다.', '정보 보호 전담 인력은 삼성전자, KT, 삼성SDS 순으로 많았다.', '공시 대상 기업 전체의 올해 정보 보호 투자액은 2조1196억원, 전담 인력은 7681.4명으로 지난해보다 각각 15.7%, 13.9% 증가했다.', '평균 투자액(29억원)과 평균 전담 인력(10.5명)도 지난해보다 늘었다.', '정보 보호에 대한 기업의 사회적 책임이 강조됨에 따라 자율 공시 기업의 수도 지난해 63개에서 91개로 늘었다.', '업종별 평균 투자액은 금융업(76억원), 정보통신업(59억원), 도소매업(27억원) 순으로 많았다.', '류제명 과학기술정보통신부 네트워크정책실장은 "정보보호 공시 제도가 기업의 정보보호 수준 제고에 기여하고 있음을 기업들의 자발적인 정보보호 투자 확대를 통해 확인할 수 있었다"며 "정부는 공시 내용 검증을 통해 정확한 정보를 이용자에게 제공할 것"이라고 말했다.']


In [10]:
# 원핫인코딩
from sklearn.preprocessing import LabelEncoder

In [14]:
data = ["사과", "배", "사과", "오렌지", "포도", "배", "사과"]
print(set(data))

{'배', '오렌지', '포도', '사과'}


In [15]:
import numpy as np

In [16]:
values = np.array(data)
print(values)

['사과' '배' '사과' '오렌지' '포도' '배' '사과']


In [17]:
# 레이블 인코딩
label_encoder = LabelEncoder() # 데이터 -> int, int 순서 -> 데이터
# fit(...), : 기준, tranform(..) : 변환
# fit_transform(..) : fit() + transform()
integer_encoded = label_encoder.fit_transform(values)

In [19]:
print(set(data))
integer_encoded

{'배', '오렌지', '포도', '사과'}


array([1, 0, 1, 2, 3, 0, 1], dtype=int64)

In [21]:
integer_encoded = integer_encoded.reshape(-1, 1)
print(integer_encoded)
print(integer_encoded.shape)

[[1]
 [0]
 [1]
 [2]
 [3]
 [0]
 [1]]
(7, 1)


In [23]:
from sklearn.preprocessing import OneHotEncoder
onehot_encoder = OneHotEncoder(sparse_output=False)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [25]:
# LabelEncoder : :invert_transform - 원핫인코딩된 값 -> 원래 범주
# numpy.argmax(...) : 가장 큰 값의 인덱스 번호

inverted = label_encoder.inverse_transform([2])
print(inverted)

['오렌지']


In [26]:
inverted = label_encoder.inverse_transform([onehot_encoded[6, :].argmax()])
print(inverted)

['배']
